# Generated by Django 5.2.1 on 2025-05-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cism_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chms_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='outside_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
